config/routes.rb
Topfood::Application.routes.draw do
  devise_for :users, controllers: {sessions: 'sessions'}

  resources :units
  resources :users
  resources :departments
  resources :positions
  resources :roles

  get '/branches/:id/sm' => 'branches#sm', as: 'sm_branches'
  post '/branches/:id/assign_sm' => 'branches#assign_sm', as: 'assign_sm_branches'

  resources :branches do
    collection do
      get   :sm
      post  :assign_sm
    end
  end

  get '/settings/:type' => "settings#index", as: 'settings'
  put '/settings/:type/update' => "settings#update", as: 'update_setting'
  resources :settings

  match '/purchase_orders/:id/approve'  => "purchase_orders#approve",   as: 'approve_purchase_orders',  via: [:get, :post]
  match '/work_orders/:id/approve'      => "work_orders#approve",       as: 'approve_work_orders',      via: [:get, :post]
  match '/employee_orders/:id/approve'  => "employee_orders#approve",   as: 'approve_employee_orders',  via: [:get, :post]

  get '/purchase_orders/:id/received'   => "purchase_orders#received",  as: 'received_purchase_orders'
  get '/work_orders/:id/received'       => "work_orders#received",      as: 'received_work_orders'
  get '/employee_orders/:id/received'   => "employee_orders#received",  as: 'received_employee_orders'

  get '/purchase_orders/:id/done'       => "purchase_orders#done",      as: 'done_purchase_orders'
  get '/work_orders/:id/done'           => "work_orders#done",          as: 'done_work_orders'
  get '/employee_orders/:id/done'       => "employee_orders#done",      as: 'done_employee_orders'

  resources :purchase_orders do
    collection do
      :approve
    end
  end
  resources :work_orders do
    collection do
      :approve
    end
  end
  resources :employee_orders do
    collection do
      :approve
    end
  end

  root :to => 'home#index'


  # API ROUTES
  namespace :api do
    devise_for :users

    put "purchase_orders/:id/approve" => "purchase_orders#approve", as: "approve_api_purchase_orders"
    put "work_orders/:id/approve"     => "work_orders#approve",     as: "approve_api_work_orders"
    put "employee_orders/:id/approve" => "employee_orders#approve", as: "approve_api_employee_orders"
    get "sync"                        => "sync#index",              as: "sync"
    get "users/:id/branches"          => "users#branches",          as: "user_branches"

    resources :units
    resources :users, only: [:index, :show]
    resources :departments
    resources :positions
    resources :roles
    resources :branches

    resources :purchase_orders do
      collection do
        post :sync
        get  :to_sync
      end
    end
    resources :work_orders do
      collection do
        post :sync
        get  :to_sync
      end
    end
    resources :employee_orders do
      collection do
        post :sync
        get  :to_sync
      end
    end
  end
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  acts_as_paranoid

  has_many :orders
  has_many :user_branches
  has_many :users, through: :user_branches

  attr_accessible :address, :name, :phone, :profile, :center
  validates :name, :address, :phone, presence: true

  scope :not_center, where("center = ? OR center IS NULL", false)

  def store_manager
    users.select{|u| u.role?('sm') }.try(:first)
  end

  def user(code)
    users.select{|u| u.role?(code) }.try(:first) || User.role?(code)
  end
end

app/controllers/api/branches_controller.rb
class Api::BranchesController < ApiController
  before_filter :find_object, :only => [:show, :update, :destroy]

  def index
    @branches = Branch.paginate(:page => params[:page])
    respond_with @branches
  end

  def show
    respond_with @branch
  end

  def create
    @branch = Branch.new(params[:branch])
    @branch.save
    respondjson @branch
  end

  def update
    @branch.update_attributes(params[:branch])
    respondjson @branch
  end

  def destroy
    @branch.destroy
    respondjson @branch
  end

  protected
    def find_object
      @branch = Branch.find(params[:id])
    end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  layout 'top-food'
  before_filter :find_object, :only => [:show, :edit, :update, :destroy, :sm, :assign_sm]

  def index
    @branches = Branch.paginate(:page => params[:page])
    respond_with @branches
  end

  def new
    @branch = Branch.new
    respond_with @branch do |format|
      format.js { render layout: false }
    end
  end

  def create
    @branch = Branch.new(params[:branch])
    flash[:notice] = 'Branch saved' if @branch.save
    respond_with @branch, location: branches_path
  end

  def show
    respond_with @branch
  end

  def edit
    respond_with @branch
  end

  def update
    flash[:notice] = 'Branch updated' if @branch.update_attributes(params[:branch])
    respond_with @branch, location: branches_path
  end

  def destroy
    flash[:notice] = @branch.destroy ? 'Branch removed' : 'Failed remove branch'
    respond_with @branch
  end

  def sm
  end

  def assign_sm
  end

  protected
    def find_object
      @branch = Branch.find(params[:id])
    end
end

app/views/branches/_branch-tab.html.erb
<div class="secondary-navigation">
  <ul class="wat-cf">
    <li class="<%= 'active' if controller_name == 'departments' %>">
      <%= link_to 'Departments', '#' %>
    </li>
    <li class="first <%= 'active' if controller_name == 'positions' %>">
      <%= link_to 'Positions', '#' %>
    </li>
    <li class="<%= 'active' if controller_name == 'departments' %>">
      <%= link_to 'Users', '#' %>
    </li>
  </ul>
</div>

app/views/branches/_form.html.erb
<%= form_for @branch, html: { class: 'form' } do |f| %>
  <%= error_messages(@branch).html_safe %>

  <div class="group">
    <%= f.label :name, 'Name', class: 'label' %>
    <%= f.text_field :name, class: 'text_field' %>
  </div>
  <div class="group">
    <%= f.label :phone, 'Phone', class: 'label' %>
    <%= f.text_field :phone, class: 'text_field' %>
  </div>
  <div class="group">
    <%= f.label :address, 'Address', class: 'label' %>
    <%= f.text_area :address, class: 'text_area', rows: 3 %>
  </div>
  <div class="group">
    <%= f.label :profile, 'Profile', class: 'label' %>
    <%= f.text_area :profile, class: 'text_area', rows: 7 %>
  </div>

  <div class="actions-bar wat-cf">
    <%= f.submit "Save", class: 'link-button' %>
    <%= link_to 'Cancel', branches_path, class: 'link-button' %>
  </div>
<% end %>

app/views/branches/edit.html.erb
<div class="content">
  <h2>Edit Branch</h2>

  <div class="inner">
    <%= render 'form' %>
  </div>
</div>

app/views/branches/index.html.erb
<div class="content">
  <h2>Branches</h2>

  <div class="inner">
    <div class="link-button-container">
      <%= link_to "New", new_branch_path, class: 'link-button' %>

      <div class="clear"></div>
    </div>

    <table class="table">
      <tr>
        <th>Name</th>
        <th>Phone</th>
        <th>Address</th>
        <th>Store Manager</th>
        <th class="last">&nbsp;</th>
      </tr>
      <% @branches.each do |branch| %>
        <tr>
          <td><%= branch.name %></td>
          <td><%= branch.phone %></td>
          <td><%= branch.address %></td>
          <td><%= branch.store_manager.try(:name) %></td>
          <td class="last">
            <%= link_to 'Show', branch_path(branch) %>
            <% unless branch.center %>
              <%= link_to 'Edit', edit_branch_path(branch) %>
              <%= link_to('Remove', branch_path(branch), method: :delete, confirm: 'Are you sure?') unless branch.center %>
            <% end %>
          </td>
        </tr>
      <% end unless @branches.blank? %>
    </table>

    <div class="actions-bar wat-cf">
      <div class-"page-entries">
        <%= page_entries_info @branches %>
      </div>
      <div class="pagination">
        <%= will_paginate %>
      </div>
    </div>

  </div>
</div>

app/views/branches/new.html.erb
<div class="content">
  <h2>New Branch</h2>

  <div class="inner">
    <%= render 'form' %>
  </div>
</div>

app/views/branches/show.html.erb
<%#= render :partial => 'branches/branch-tab.html' %>
<div class="content">
  <h2>Branch</h2>

  <div class="inner">
    <p>
      <%= label_tag :name, 'Name', class: 'detail-label' %>
      <span>: <%= @branch.name %></span>
    </p>
    <p>
      <%= label_tag :phone, 'Phone', class: 'detail-label' %>
      <span>: <%= @branch.phone %></span>
    </p>
    <p>
      <%= label_tag :address, 'Address', class: 'detail-label' %>
      <span>: <%= @branch.address %></span>
    </p>
    <p>
      <%= label_tag :profile, 'Profile', class: 'detail-label' %>
      <span>: <%= @branch.profile %></span>
    </p>
    <p>
      <%= label_tag :store_manager, 'Store Manager', class: 'detail-label' %>
      <span>: <%= @branch.store_manager.try(:name) %></span>
    </p>
    <p>
      <%= label_tag :team_leader, 'Team Leader', class: 'detail-label' %>
      <span>: <%= @branch.user('tl').try(:name) %></span>
    </p>
    <p>
      <%= label_tag :manager, 'Manager', class: 'detail-label' %>
      <span>: <%= @branch.user('mng').try(:name) %></span>
    </p>
    <p>
      <%= label_tag :general_manager, 'General Manager', class: 'detail-label' %>
      <span>: <%= @branch.user('gm').try(:name) %></span>
    </p>

    <div class="link-button-container">
      <%= link_to "Back", branches_path, class: 'link-button' %>

      <div class="clear"></div>
    </div>
  </div>
</div>

app/views/branches/sm.html.erb
<div class="content">
  <h2>Assign Store Manage for Branch <%= @branch.name %></h2>

  <div class="inner">
    <%= form_for 'sm', url: assign_sm_branches_path(@branch), html: { class: 'form' } do |f| %>
      <div class="group">
        <%= f.label :user, 'User', class: 'label' %>
        <%= f.select :user_id, options_for_select([]), {}, class: 'selectbox' %>
      </div>


      <div class="actions-bar wat-cf">
        <%= f.submit "Save", class: 'link-button' %>
        <%= link_to 'Back', (:back || branches_path), class: 'link-button' %>
      </div>
    <% end %>
  </div>
</div>