config/routes.rb
Topfood::Application.routes.draw do
  devise_for :users, controllers: {sessions: 'sessions'}

  resources :units
  resources :users
  resources :departments
  resources :positions
  resources :roles

  get '/branches/:id/sm' => 'branches#sm', as: 'sm_branches'
  post '/branches/:id/assign_sm' => 'branches#assign_sm', as: 'assign_sm_branches'

  resources :branches do
    collection do
      get   :sm
      post  :assign_sm
    end
  end

  get '/settings/:type' => "settings#index", as: 'settings'
  put '/settings/:type/update' => "settings#update", as: 'update_setting'
  resources :settings

  match '/purchase_orders/:id/approve'  => "purchase_orders#approve",   as: 'approve_purchase_orders',  via: [:get, :post]
  match '/work_orders/:id/approve'      => "work_orders#approve",       as: 'approve_work_orders',      via: [:get, :post]
  match '/employee_orders/:id/approve'  => "employee_orders#approve",   as: 'approve_employee_orders',  via: [:get, :post]

  get '/purchase_orders/:id/received'   => "purchase_orders#received",  as: 'received_purchase_orders'
  get '/work_orders/:id/received'       => "work_orders#received",      as: 'received_work_orders'
  get '/employee_orders/:id/received'   => "employee_orders#received",  as: 'received_employee_orders'

  get '/purchase_orders/:id/done'       => "purchase_orders#done",      as: 'done_purchase_orders'
  get '/work_orders/:id/done'           => "work_orders#done",          as: 'done_work_orders'
  get '/employee_orders/:id/done'       => "employee_orders#done",      as: 'done_employee_orders'

  resources :purchase_orders do
    collection do
      :approve
    end
  end
  resources :work_orders do
    collection do
      :approve
    end
  end
  resources :employee_orders do
    collection do
      :approve
    end
  end

  root :to => 'home#index'


  # API ROUTES
  namespace :api do
    devise_for :users

    put "purchase_orders/:id/approve" => "purchase_orders#approve", as: "approve_api_purchase_orders"
    put "work_orders/:id/approve"     => "work_orders#approve",     as: "approve_api_work_orders"
    put "employee_orders/:id/approve" => "employee_orders#approve", as: "approve_api_employee_orders"
    get "sync"                        => "sync#index",              as: "sync"
    get "users/:id/branches"          => "users#branches",          as: "user_branches"

    resources :units
    resources :users, only: [:index, :show]
    resources :departments
    resources :positions
    resources :roles
    resources :branches

    resources :purchase_orders do
      collection do
        post :sync
        get  :to_sync
      end
    end
    resources :work_orders do
      collection do
        post :sync
        get  :to_sync
      end
    end
    resources :employee_orders do
      collection do
        post :sync
        get  :to_sync
      end
    end
  end
end

app/models/position.rb
class Position < ActiveRecord::Base
  acts_as_paranoid

  has_many :employee_details
  attr_accessible :code, :name, :description
  validates :code, :name, presence: true
end

app/controllers/api/positions_controller.rb
class Api::PositionsController < ApiController
  before_filter :find_object, :only => [:show, :update, :destroy]

  def index
    @positions = Position.paginate(:page => params[:page])
    respond_with @positions
  end

  def create
    @position = Position.new(params[:position])
    @position.save
    respondjson @position
  end

  def update
    @position.update_attributes(params[:position])
    respondjson @position
  end

  def destroy
    @position.destroy
    respondjson @position
  end

  protected
    def find_object
      @position = Position.find_by_code(params[:id])
    end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  layout 'top-food'
  before_filter :find_object, :only => [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @positions = Position.paginate(:page => params[:page])
    respond_with @positions
  end

  def new
    @position = Position.new
    respond_with @position do |format|
      format.js { render layout: false }
    end
  end

  def create
    @position = Position.new(params[:position])
    flash[:notice] = 'Position saved' if @position.save
    respond_with @position, location: positions_path
  end

  def edit
    respond_with @position
  end

  def update
    flash[:notice] = 'Position updated' if @position.update_attributes(params[:position])
    respond_with @position, location: positions_path
  end

  def destroy
    flash[:notice] = @position.destroy ? 'Position removed' : 'Failed remove position'
    respond_with @position
  end

  protected
    def find_object
      @position = Position.find(params[:id])
    end
end

app/views/positions/_form.html.erb
<%= form_for @position, html: { class: 'form' } do |f| %>
  <%= error_messages(@position).html_safe %>

  <div class="group">
    <%= f.label :code, 'Code', class: 'label' %>
    <%= f.text_field :code, class: 'text_field' %>
  </div>
  <div class="group">
    <%= f.label :name, 'Name', class: 'label' %>
    <%= f.text_field :name, class: 'text_field' %>
  </div>
  <div class="group">
    <%= f.label :description, 'Description', class: 'label' %>
    <%= f.text_area :description, class: 'text_area', rows: 3 %>
  </div>

  <div class="actions-bar wat-cf">
    <%= f.submit "Save", class: 'link-button' %>
    <%= link_to 'Cancel', positions_path, class: 'link-button' %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<%= render 'shared/master-tab.html.erb' %>
<div class="content">
  <h2>Edit Position</h2>

  <div class="inner">
    <%= render 'form' %>
  </div>
</div>

app/views/positions/index.html.erb
<%= render 'shared/master-tab.html.erb' %>
<div class="content">
  <h2>Position</h2>

  <div class="inner">
    <div class="link-button-container">
      <%= link_to "New", new_position_path, class: 'link-button' %>

      <div class="clear"></div>
    </div>

    <table class="table">
      <tr>
        <th>Code</th>
        <th>Name</th>
        <th class="last">&nbsp;</th>
      </tr>
      <% @positions.each do |p| %>
        <tr>
          <td><%= p.code %></td>
          <td><%= p.name %></td>
          <td class="last">
            <%= link_to 'Edit', edit_position_path(p) %>
            <%= link_to 'Remove', position_path(p), method: :delete, confirm: 'Are you sure?' %>
          </td>
        </tr>
      <% end unless @positions.blank? %>
    </table>

    <div class="actions-bar wat-cf">
      <div class-"page-entries">
        <%= page_entries_info @positions %>
      </div>
      <div class="pagination">
        <%= will_paginate %>
      </div>
    </div>

  </div>
</div>

app/views/positions/new.html.erb
<%= render 'shared/master-tab.html.erb' %>
<div class="content">
  <h2>New Position</h2>

  <div class="inner">
    <%= render 'form' %>
  </div>
</div>