config/routes.rb
Topfood::Application.routes.draw do
  devise_for :users, controllers: {sessions: 'sessions'}

  resources :units
  resources :users
  resources :departments
  resources :positions
  resources :roles

  get '/branches/:id/sm' => 'branches#sm', as: 'sm_branches'
  post '/branches/:id/assign_sm' => 'branches#assign_sm', as: 'assign_sm_branches'

  resources :branches do
    collection do
      get   :sm
      post  :assign_sm
    end
  end

  get '/settings/:type' => "settings#index", as: 'settings'
  put '/settings/:type/update' => "settings#update", as: 'update_setting'
  resources :settings

  match '/purchase_orders/:id/approve'  => "purchase_orders#approve",   as: 'approve_purchase_orders',  via: [:get, :post]
  match '/work_orders/:id/approve'      => "work_orders#approve",       as: 'approve_work_orders',      via: [:get, :post]
  match '/employee_orders/:id/approve'  => "employee_orders#approve",   as: 'approve_employee_orders',  via: [:get, :post]

  get '/purchase_orders/:id/received'   => "purchase_orders#received",  as: 'received_purchase_orders'
  get '/work_orders/:id/received'       => "work_orders#received",      as: 'received_work_orders'
  get '/employee_orders/:id/received'   => "employee_orders#received",  as: 'received_employee_orders'

  get '/purchase_orders/:id/done'       => "purchase_orders#done",      as: 'done_purchase_orders'
  get '/work_orders/:id/done'           => "work_orders#done",          as: 'done_work_orders'
  get '/employee_orders/:id/done'       => "employee_orders#done",      as: 'done_employee_orders'

  resources :purchase_orders do
    collection do
      :approve
    end
  end
  resources :work_orders do
    collection do
      :approve
    end
  end
  resources :employee_orders do
    collection do
      :approve
    end
  end

  root :to => 'home#index'


  # API ROUTES
  namespace :api do
    devise_for :users

    put "purchase_orders/:id/approve" => "purchase_orders#approve", as: "approve_api_purchase_orders"
    put "work_orders/:id/approve"     => "work_orders#approve",     as: "approve_api_work_orders"
    put "employee_orders/:id/approve" => "employee_orders#approve", as: "approve_api_employee_orders"
    get "sync"                        => "sync#index",              as: "sync"
    get "users/:id/branches"          => "users#branches",          as: "user_branches"

    resources :units
    resources :users, only: [:index, :show]
    resources :departments
    resources :positions
    resources :roles
    resources :branches

    resources :purchase_orders do
      collection do
        post :sync
        get  :to_sync
      end
    end
    resources :work_orders do
      collection do
        post :sync
        get  :to_sync
      end
    end
    resources :employee_orders do
      collection do
        post :sync
        get  :to_sync
      end
    end
  end
end

app/views/shared/_approval.html.erb
<h3>Approvals</h3>
<% @order.approvals.each_with_index do |app, idx| %>
  <div class="approval-status">
    <b>Approval <%= idx+1 %></b><br /><br />

    <span class="<%= app.status.downcase %>"><%= app.status %></span><br />
    <%= "<span class='grey'>#{date_time_format app.do_at}</span>".html_safe unless app.pending %>
    <% if @order.show_link_for(current_user, app) %>
      <%= link_to "Approve", send("approve_#{@order.type.underscore.pluralize}_path", app, approved: 1), :class => 'green' %>
      <%= link_to "Reject", '#reject', :class => 'red rejected-button' %>
    <% end %>
    <br /><br />

    <b><%= app.user.name %></b><br />
    <span class="grey">(<%= app.role.name %>)</span>
  </div>
<% end %>

app/views/shared/_implementer-element.html.erb
<div class="implementer-status-container">
  <div class="implementer-status">
    <b>Received</b><br /><br />

    <% if @order.implement_status.blank? %>
      <br />
      <% if can?(:received, @order) %>
        <%= link_to("Received", send("received_#{@order.type.underscore.pluralize}_path", @order), class: 'yellow') %>
      <% else %>
        <span class="grey">Waiting</span>
      <% end %>
    <% end %>

    <% if @order.received_at %>
      <span class="yellow">Received</span><br />
      <%= "<span class='grey'>#{date_time_format @order.received_at}</span>".html_safe %>
    <% end %>
    <br /><br />

    <b>&nbsp;</b><br />
    <span class="grey">&nbsp;</span>
  </div>

  <div class="implementer-status">
    <b>Done</b><br /><br />

    <% if can?(:done, @order) && @order.received? %>
      <br /><%= link_to "DONE", send("done_#{@order.type.underscore.pluralize}_path", @order), class: 'green' %>
    <% end %>
    <% if cannot?(:done, @order) && !@order.done? %>
      <br /><span class="grey">Waiting</span>
    <% end %>

    <% if @order.done? %>
      <span class="green">DONE</span><br />
      <%= "<span class='grey'>#{date_time_format @order.done_at}</span>".html_safe %>
    <% end %>
    <br /><br />

    <b>&nbsp;</b><br />
    <span class="grey">&nbsp;</span>
  </div>
</div>

app/views/shared/_master-tab.html.erb
<div class="secondary-navigation">
  <ul class="wat-cf">
    <li class="<%= 'active' if controller_name == 'departments' %>">
      <%= link_to 'Departments', departments_path %>
    </li>
    <li class="<%= 'active' if controller_name == 'positions' %>">
      <%= link_to 'Positions', positions_path %>
    </li>
    <li class="<%= 'active' if controller_name == 'units' %>">
      <%= link_to 'Unit', units_path %>
    </li>
  </ul>
</div>

app/views/shared/_orders-tab.html.erb
<div class="secondary-navigation">
  <ul class="wat-cf">
    <li class="<%= 'active' if controller_name == 'purchase_orders' %>">
      <%= link_to 'Purchase Orders', purchase_orders_path %>
    </li>
    <li class="<%= 'active' if controller_name == 'work_orders' %>">
      <%= link_to 'Work Order', work_orders_path %>
    </li>
    <li class="<%= 'active' if controller_name == 'employee_orders' %>">
      <%= link_to 'Employee Orders', employee_orders_path %>
    </li>
  </ul>
</div>

app/views/shared/_reject-form.html.erb
<% if @order.next_approval %>
  <div class="reject-form-container">
    <%= form_for :approved, url: send("approve_#{@order.type.underscore.pluralize}_path", @order.next_approval), html: { class: 'form reject-form' } do |f| %>
      <%= hidden_field_tag :approved, '0' %>
      <%= label_tag "Please write sejected reason" %>:<br />
      <%= text_area_tag :reason, '', cols: 80, rows: 2, placeholder: "Rejected Reason", class: "text_area", required: 'required' %>
      <br />
      <%= f.submit 'Save', class: 'link-button' %>
      <%= link_to "Cancel", "#cancel-rejection", class: 'link-button cancel-rejection' %>
    <% end %>
  </div>
<% end %>

<% if @order.rejected? %>
  <div class="rejected-reason">
    <b>Rejected Reason:</b>
    <p><%= @order.rejected_reason %></p>
  </div>
<% end %>

app/views/shared/_settings-tab.html.erb
<div class="secondary-navigation">
  <ul class="wat-cf">
    <li class="<%= 'active' if @type == 'PurchaseOrder' %>">
      <%= link_to 'Purchase Order', settings_path('purchase') %>
    </li>
    <li class="<%= 'active' if @type == 'WorkOrder' %>">
      <%= link_to 'Work Order', settings_path('work') %>
    </li>
    <li class="<%= 'active' if @type == 'EmployeeOrder' %>">
      <%= link_to 'Employee', settings_path('employee') %>
    </li>
  </ul>
</div>