config/routes.rb
Topfood::Application.routes.draw do
  devise_for :users, controllers: {sessions: 'sessions'}

  resources :units
  resources :users
  resources :departments
  resources :positions
  resources :roles

  get '/branches/:id/sm' => 'branches#sm', as: 'sm_branches'
  post '/branches/:id/assign_sm' => 'branches#assign_sm', as: 'assign_sm_branches'

  resources :branches do
    collection do
      get   :sm
      post  :assign_sm
    end
  end

  get '/settings/:type' => "settings#index", as: 'settings'
  put '/settings/:type/update' => "settings#update", as: 'update_setting'
  resources :settings

  match '/purchase_orders/:id/approve'  => "purchase_orders#approve",   as: 'approve_purchase_orders',  via: [:get, :post]
  match '/work_orders/:id/approve'      => "work_orders#approve",       as: 'approve_work_orders',      via: [:get, :post]
  match '/employee_orders/:id/approve'  => "employee_orders#approve",   as: 'approve_employee_orders',  via: [:get, :post]

  get '/purchase_orders/:id/received'   => "purchase_orders#received",  as: 'received_purchase_orders'
  get '/work_orders/:id/received'       => "work_orders#received",      as: 'received_work_orders'
  get '/employee_orders/:id/received'   => "employee_orders#received",  as: 'received_employee_orders'

  get '/purchase_orders/:id/done'       => "purchase_orders#done",      as: 'done_purchase_orders'
  get '/work_orders/:id/done'           => "work_orders#done",          as: 'done_work_orders'
  get '/employee_orders/:id/done'       => "employee_orders#done",      as: 'done_employee_orders'

  resources :purchase_orders do
    collection do
      :approve
    end
  end
  resources :work_orders do
    collection do
      :approve
    end
  end
  resources :employee_orders do
    collection do
      :approve
    end
  end

  root :to => 'home#index'


  # API ROUTES
  namespace :api do
    devise_for :users

    put "purchase_orders/:id/approve" => "purchase_orders#approve", as: "approve_api_purchase_orders"
    put "work_orders/:id/approve"     => "work_orders#approve",     as: "approve_api_work_orders"
    put "employee_orders/:id/approve" => "employee_orders#approve", as: "approve_api_employee_orders"
    get "sync"                        => "sync#index",              as: "sync"
    get "users/:id/branches"          => "users#branches",          as: "user_branches"

    resources :units
    resources :users, only: [:index, :show]
    resources :departments
    resources :positions
    resources :roles
    resources :branches

    resources :purchase_orders do
      collection do
        post :sync
        get  :to_sync
      end
    end
    resources :work_orders do
      collection do
        post :sync
        get  :to_sync
      end
    end
    resources :employee_orders do
      collection do
        post :sync
        get  :to_sync
      end
    end
  end
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  acts_as_paranoid

  has_many :order_details

  attr_accessible :code, :name
  validates :code, :name, presence: true
  validates :code, uniqueness: true
end

app/controllers/api/units_controller.rb
class Api::UnitsController < ApiController
  before_filter :find_object, :only => [:show, :update, :destroy]

  def index
    @units = Unit.paginate(:page => params[:page])
    respond_with @units
  end

  def create
    @unit = Unit.new(params[:unit])
    @unit.save
    respondjson @unit
  end

  def update
    @unit.update_attributes(params[:unit])
    respondjson @unit
  end

  def destroy
    @unit.destroy
    respondjson @unit
  end

  protected
    def find_object
      @unit = Unit.find_by_code(params[:id])
    end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  layout 'top-food'
  before_filter :find_object, :only => [:show, :edit, :update, :destroy]

  def index
    @units = Unit.paginate(:page => params[:page])
    respond_with @units
  end

  def new
    @unit = Unit.new
    respond_with @unit do |format|
      format.js { render layout: false }
    end
  end

  def create
    @unit = Unit.new(params[:unit])
    flash[:notice] = 'Unit saved' if @unit.save
    respond_with @unit, location: units_path
  end

  def edit
    respond_with @unit
  end

  def update
    flash[:notice] = 'Unit updated' if @unit.update_attributes(params[:unit])
    respond_with @unit, location: units_path
  end

  def destroy
    flash[:notice] = @unit.destroy ? 'Unit removed' : 'Failed remove unit'
    respond_with @unit
  end

  protected
    def find_object
      @unit = Unit.find(params[:id])
    end
end

app/views/units/_form.html.erb
<%= form_for @unit, html: { class: 'form' } do |f| %>
  <%= error_messages(@unit).html_safe %>

  <div class="group">
    <%= f.label :code, 'Code', class: 'label' %>
    <%= f.text_field :code, class: 'text_field' %>
  </div>
  <div class="group">
    <%= f.label :name, 'Name', class: 'label' %>
    <%= f.text_field :name, class: 'text_field' %>
  </div>

  <div class="actions-bar wat-cf">
    <%= f.submit "Save", class: 'link-button' %>
    <%= link_to 'Cancel', units_path, class: 'link-button' %>
  </div>
<% end %>

app/views/units/edit.html.erb
<%= render 'shared/master-tab.html.erb' %>
<div class="content">
  <h2>Edit Unit</h2>

  <div class="inner">
    <%= render 'form' %>
  </div>
</div>

app/views/units/index.html.erb
<%= render 'shared/master-tab.html.erb' %>
<div class="content">
  <h2>Unit</h2>

  <div class="inner">
    <div class="link-button-container">
      <%= link_to "New", new_unit_path, class: 'link-button' %>

      <div class="clear"></div>
    </div>

    <table class="table">
      <tr>
        <th>Code</th>
        <th>Name</th>
        <th class="last">&nbsp;</th>
      </tr>
      <% @units.each do |unit| %>
        <tr>
          <td><%= unit.code %></td>
          <td><%= unit.name %></td>
          <td class="last">
            <%= link_to 'Edit', edit_unit_path(unit) %>
            <%= link_to 'Remove', unit_path(unit), method: :delete, confirm: 'Are you sure?' %>
          </td>
        </tr>
      <% end unless @units.blank? %>
    </table>

    <div class="actions-bar wat-cf">
      <div class-"page-entries">
        <%= page_entries_info @units %>
      </div>
      <div class="pagination">
        <%= will_paginate %>
      </div>
    </div>

  </div>
</div>

app/views/units/new.html.erb
<div class="content">
  <h2>New Unit</h2>

  <div class="inner">
    <%= render 'form' %>
  </div>
</div>